### ISSUE TITLE
Suggest tf2 equivalent version of these modules

### ISSUE THREAD

**Issue by ucalyptus2** [titu1994/tf_neural_deconvolution#3]
from tensorflow.python.keras.layers.convolutional import Conv
from tensorflow.python.keras.utils import conv_utils

Can Replacing Conv with tf.keras.layers.Layer work?

**Comment by ucalyptus2** [comment]
@titu1994

**Comment by titu1994** [comment]
No, it won't. Deconvolution is an operation performed just prior to convolution op, so it needs to inherits from Conv.

**Comment by ucalyptus2** [comment]
Thank you for the clarification.
